{% set name = "perl-sub-name" %}
{% set version = "0.28" %}
{% set sha256 = "39c53f6b3b02cbc73176564413b51d3c0f375f9760983fd579c27f558b169cfc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Sub-Name-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 1
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Sub::Name

about:
  home: https://github.com/p5sagit/Sub-Name
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: (Re)name a sub

extra:
  recipe-maintainers:
    - dslarm
    - xileF1337
    - conda-forge/perl-packagers
    - dslarm
